
list_events:
    path:     /
    defaults: { _controller: AppBundle:Event:listEvents }

create_event:
    path:     /createEvent
    defaults: { _controller: AppBundle:Event:createEvent }

show_event:
    path:     /showEvent
    defaults: { _controller: AppBundle:Event:showEvent }

    # redirecting the user home
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: list_events
        permanent: true
